server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: monitoring_v2

  datasource:
    url: ${DB_URL}
    username:  ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6375}
      password: ${REDIS_PASSWORD:}
      
  threads:
    virtual:
      enabled: true
  
  #  flyway:
#    enabled: false
#    locations: classpath:db/migration

  jackson:
    default-property-inclusion: non_null

anomaly:
  base-url: ${ANOMALY_API_BASE_URL:http://127.0.0.1:5001}
  api-key: ${ANOMALY_API_KEY:}
  confirm: 2

  websocket:
    topic: "/topic/metrics"

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com:
      elkassimi:
        monitoring_v2_0:
          websocket:
            RealTimePushService: TRACE

app:
  security:
    jwt-secret: ${JWT_SECRET:CqG349LQVPaCdhpnwEpweSknFMGadqrSQVi67S30SHDmlJW87AHHFLxa3ficqs1Dnzq4z7+ewDB2vFWUBtIxWA}
    user-token-lifetime: ${JWT_USER_TOKEN_LIFETIME:PT8H}
